package_rename_config:
  android:
    app_name: Salah Time
    package_name: com.jazakallah.salah_time
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: Salah Time
    bundle_name: com.jazakallah.salah_time
    package_name: com.jazakallah.salah_time
